
// ++++++++++++++++++++
// Day 1
// try{
//     let x = undefined
//     console.log(x[0]);
// }
// catch(err){
//     console.log("error is in catch");
// }
// finally{
//     console.log("always executed");
// }

// +++++++++++++++++
// Day 2

try{
    console.log("hello");
    console.log(a);
    console.log("ending try");
}
catch (err){
    console.log("handled");
}
finally{
    console.log("finally");
}
console.log("end");